#!/bin/sh

PT=8022

echo $1
# Copy
for d in supannn julia menger srray
do
    echo $d
    ssh -p $PT $1 "mkdir -p $d/src"
    scp -P $PT ./$d/Cargo.toml $1:$d/Cargo.toml
    scp -P $PT ./$d/src/*.rs $1:$d/src/
done
# Compile
for d in supannn julia menger
do
    echo $d
    ssh -p $PT $1 "mkdir -p $d/src"
    scp -P $PT ./$d/Cargo.toml $1:$d/Cargo.toml
    scp -P $PT ./$d/src/*.rs $1:$d/src/
    ssh -p $PT $1 -- "cd ./$d; cargo --offline build --release"
    ssh -p $PT $1 "ln -sf ../$d/target/release/$d ./supannn/$d"
done
# Allow list
scp -P $PT ./supannn/apps.txt $1:./supannn/apps.txt
